name: CI-CD-Pipeline-to-AWS-EB
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-tromanovskiy"
  EB_APPLICATION_NAME       : "my-app"
  EB_ENVIRONMENT_NAME       : "Myapp-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  
on:
  push:
    branches: [ "main" ]

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo  
      uses: actions/checkout@v1

    - name: Create deployment ackage
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    - name: view  
      run : ls -al
    
